name: read_more_codespark
description: "Tired of truncated text? read_more_codespark offers a simple and customizable solution for displaying expandable text in your Flutter projects."
version: 0.0.11
homepage: https://github.com/Katayath-Sai-Kiran/read_more_codespark.git

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

screenshots:

  - path: assets/300x650-01.png
    description: Initial Text
    width: 300

  - path: assets/300x650-02.png
    description: Expanded Text
    width: 300

  - path: assets/300x650-03.png
    description: Sample Code
    width: 300



  
